### ISSUE TITLE
templates defined here but rendering tested in CLI repo's codebase

### ISSUE THREAD

**Issue by jaketf** [massdriver-cloud/application-templates#13]
we should come up with a solution where we can have standalone test coverage in this repo.

an issue right now is that we do not properly trim whitespace so we end up with rendered templates with a bunch of extra newlines which is sloppy. 

we can only recognize this once we run the rendering tests in the CLI.

**Comment by coryodaniel** [comment]
The CLI shouldn't test using this repo. It should have basic happy path tests and error recovery tests (maybe in the event of a file being present). 

If we sync this repo into the CLI it's going to get massively bloated and make the tests fragile.
